import type { ConfigSchema, PackageBootstrapModule } from "../../core/types.ts";

const configSchema: ConfigSchema = {
  module: "matrix",
  label: "Matrix Platform",
  fields: [
    {
      key: "matrix.homeserverUrl",
      label: "Matrix Homeserver URL",
      description: "Example: https://matrix.org",
      type: "string",
      required: true,
      env: "MATRIX_HOMESERVER_URL",
      flag: "matrix-homeserver-url",
    },
    {
      key: "matrix.accessToken",
      label: "Matrix Access Token",
      description: "Access token for the bot account",
      type: "string",
      required: true,
      secret: true,
      env: "MATRIX_ACCESS_TOKEN",
      flag: "matrix-access-token",
    },
    {
      key: "matrix.userId",
      label: "Matrix User ID",
      description: "Example: @missy:matrix.org",
      type: "string",
      required: true,
      env: "MATRIX_USER_ID",
      flag: "matrix-user-id",
    },
    {
      key: "matrix.deviceId",
      label: "Matrix Device ID",
      description: "Optional device ID associated with the access token",
      type: "string",
      required: false,
      env: "MATRIX_DEVICE_ID",
      flag: "matrix-device-id",
    },
    {
      key: "matrix.roomIds",
      label: "Matrix Room IDs",
      description: "Comma-separated room IDs or aliases to join on startup",
      type: "string",
      required: false,
      default: "",
      env: "MATRIX_ROOM_IDS",
      flag: "matrix-room-ids",
    },
    {
      key: "matrix.commandPrefix",
      label: "Command Prefix",
      description: "Prefix for Matrix text commands",
      type: "string",
      required: false,
      default: "!M!",
      env: "MATRIX_COMMAND_PREFIX",
      flag: "matrix-command-prefix",
    },
    {
      key: "matrix.displayName",
      label: "Matrix Display Name",
      description: "Display name used for plain-text mentions",
      type: "string",
      required: false,
      default: "Missy",
      env: "MATRIX_DISPLAY_NAME",
      flag: "matrix-display-name",
    },
    {
      key: "matrix.mentionOnly",
      label: "Mention Only",
      description: "Only respond in rooms when mentioned",
      type: "boolean",
      required: false,
      default: true,
      hidden: true,
      env: "MATRIX_MENTION_ONLY",
      flag: "matrix-mention-only",
    },
    {
      key: "matrix.respondToAllMessages",
      label: "Respond to All Messages",
      description: "Respond to every message in Matrix rooms",
      type: "boolean",
      required: false,
      default: false,
      hidden: true,
      env: "MATRIX_RESPOND_TO_ALL_MESSAGES",
      flag: "matrix-respond-to-all-messages",
    },
    {
      key: "matrix.maxMessageLength",
      label: "Max Message Length",
      description: "Maximum characters per Matrix message",
      type: "number",
      required: false,
      default: 0,
      hidden: true,
      env: "MATRIX_MAX_MESSAGE_LENGTH",
      flag: "matrix-max-message-length",
    },
    {
      key: "matrix.autoJoinInvites",
      label: "Auto-Join Invites",
      description: "Automatically join rooms the bot is invited to",
      type: "boolean",
      required: false,
      default: true,
      hidden: true,
      env: "MATRIX_AUTO_JOIN_INVITES",
      flag: "matrix-auto-join-invites",
    },
  ],
};

const bootstrap: PackageBootstrapModule = {
  metadata: {
    name: "matrix",
    description: "Matrix platform adapter backed by matrix-js-sdk.",
    version: "0.1.0",
  },
  kind: "platform",
  modulePath: "src/mod.ts",
  configSchema,
};

export default bootstrap;
