import type { ConfigSchema, PackageBootstrapModule } from "../../core/types.ts";

const configSchema: ConfigSchema = {
  module: "matrix",
  label: "Matrix Platform",
  fields: [
    {
      key: "matrix.homeserverUrl",
      label: "Matrix Homeserver URL",
      description: "Example: https://matrix.org",
      type: "string",
      required: true,
      env: "MATRIX_HOMESERVER_URL",
      flag: "matrix-homeserver-url",
    },
    {
      key: "matrix.accessToken",
      label: "Matrix Access Token",
      description: "Existing access token for the bot account; optional when username/password are set",
      type: "string",
      required: false,
      secret: true,
      env: "MATRIX_ACCESS_TOKEN",
      flag: "matrix-access-token",
    },
    {
      key: "matrix.username",
      label: "Matrix Username",
      description: "Bot Matrix username or user ID for automatic device login",
      type: "string",
      required: false,
      env: "MATRIX_USERNAME",
      flag: "matrix-username",
    },
    {
      key: "matrix.password",
      label: "Matrix Password",
      description: "Bot Matrix password for automatic Missy device login",
      type: "string",
      required: false,
      secret: true,
      env: "MATRIX_PASSWORD",
      flag: "matrix-password",
    },
    {
      key: "matrix.userId",
      label: "Matrix User ID",
      description: "Example: @missy:matrix.org; optional when username/password are set",
      type: "string",
      required: false,
      env: "MATRIX_USER_ID",
      flag: "matrix-user-id",
    },
    {
      key: "matrix.deviceId",
      label: "Matrix Device ID",
      description: "Optional device ID associated with the access token",
      type: "string",
      required: false,
      env: "MATRIX_DEVICE_ID",
      flag: "matrix-device-id",
    },
    {
      key: "matrix.recoveryKey",
      label: "Matrix Recovery Key",
      description: "Recovery/security key used to unlock Matrix secret storage and key backup",
      type: "string",
      required: false,
      secret: true,
      env: "MATRIX_RECOVERY_KEY",
      flag: "matrix-recovery-key",
    },
    {
      key: "matrix.restoreKeyBackup",
      label: "Restore Matrix Key Backup",
      description: "Restore server-side room keys on startup when a recovery key is configured",
      type: "boolean",
      required: false,
      default: true,
      hidden: true,
      env: "MATRIX_RESTORE_KEY_BACKUP",
      flag: "matrix-restore-key-backup",
    },
    {
      key: "matrix.verifyDevice",
      label: "Verify Matrix Device",
      description: "Request interactive SAS verification for the current Matrix device on startup",
      type: "boolean",
      required: false,
      default: true,
      hidden: true,
      env: "MATRIX_VERIFY_DEVICE",
      flag: "matrix-verify-device",
    },
    {
      key: "matrix.deviceDisplayName",
      label: "Matrix Device Display Name",
      description: "Display name for the automatically-created Matrix device",
      type: "string",
      required: false,
      default: "Missy Bot",
      env: "MATRIX_DEVICE_DISPLAY_NAME",
      flag: "matrix-device-display-name",
    },
    {
      key: "matrix.roomIds",
      label: "Matrix Room IDs",
      description: "Comma-separated room IDs or aliases to join on startup",
      type: "string",
      required: false,
      default: "",
      env: "MATRIX_ROOM_IDS",
      flag: "matrix-room-ids",
    },
    {
      key: "matrix.commandPrefix",
      label: "Command Prefix",
      description: "Prefix for Matrix text commands",
      type: "string",
      required: false,
      default: "!M!",
      env: "MATRIX_COMMAND_PREFIX",
      flag: "matrix-command-prefix",
    },
    {
      key: "matrix.displayName",
      label: "Matrix Display Name",
      description: "Display name used for plain-text mentions",
      type: "string",
      required: false,
      default: "Missy",
      env: "MATRIX_DISPLAY_NAME",
      flag: "matrix-display-name",
    },
    {
      key: "matrix.mentionOnly",
      label: "Mention Only",
      description: "Only respond in rooms when mentioned",
      type: "boolean",
      required: false,
      default: true,
      hidden: true,
      env: "MATRIX_MENTION_ONLY",
      flag: "matrix-mention-only",
    },
    {
      key: "matrix.respondToAllMessages",
      label: "Respond to All Messages",
      description: "Respond to every message in Matrix rooms",
      type: "boolean",
      required: false,
      default: false,
      hidden: true,
      env: "MATRIX_RESPOND_TO_ALL_MESSAGES",
      flag: "matrix-respond-to-all-messages",
    },
    {
      key: "matrix.maxMessageLength",
      label: "Max Message Length",
      description: "Maximum characters per Matrix message",
      type: "number",
      required: false,
      default: 0,
      hidden: true,
      env: "MATRIX_MAX_MESSAGE_LENGTH",
      flag: "matrix-max-message-length",
    },
    {
      key: "matrix.autoJoinInvites",
      label: "Auto-Join Invites",
      description: "Automatically join rooms the bot is invited to",
      type: "boolean",
      required: false,
      default: true,
      hidden: true,
      env: "MATRIX_AUTO_JOIN_INVITES",
      flag: "matrix-auto-join-invites",
    },
  ],
};

const bootstrap: PackageBootstrapModule = {
  metadata: {
    name: "matrix",
    description: "Matrix platform adapter backed by matrix-bot-sdk.",
    version: "0.2.0",
  },
  kind: "platform",
  modulePath: "src/mod.ts",
  configSchema,
};

export default bootstrap;
