import type { ConfigSchema, PackageBootstrapModule } from "../../core/types.ts";

const configSchema: ConfigSchema = {
  module: "signal",
  label: "Signal Platform",
  fields: [
    {
      key: "signal.account",
      label: "Signal Account",
      description: "Phone number registered with signal-cli (e.g. +1234567890)",
      type: "string",
      required: true,
      env: "SIGNAL_ACCOUNT",
      flag: "signal-account",
    },
    {
      key: "signal.socketPath",
      label: "Signal Daemon Socket Path",
      description:
        "Path to the signal-cli daemon JSON-RPC socket (UNIX) or host:port (TCP). Defaults to $XDG_RUNTIME_DIR/signal-cli/socket on UNIX, or localhost:7583 on Windows.",
      type: "string",
      required: false,
      env: "SIGNAL_SOCKET_PATH",
      flag: "signal-socket-path",
    },
    {
      key: "signal.commandPrefix",
      label: "Command Prefix",
      description: "Prefix for text commands",
      type: "string",
      required: false,
      default: "!M!",
      env: "SIGNAL_COMMAND_PREFIX",
      flag: "signal-command-prefix",
    },
    {
      key: "signal.displayName",
      label: "Signal Display Name",
      description: "Display name referenced in mention patterns",
      type: "string",
      required: false,
      default: "Missy",
      env: "SIGNAL_DISPLAY_NAME",
      flag: "signal-display-name",
    },
    {
      key: "signal.mentionOnly",
      label: "Mention Only",
      description: "Only respond in groups when mentioned",
      type: "boolean",
      required: false,
      default: true,
      hidden: true,
      env: "SIGNAL_MENTION_ONLY",
      flag: "signal-mention-only",
    },
    {
      key: "signal.respondToAllMessages",
      label: "Respond to All Messages",
      description: "Respond to every message in Signal groups",
      type: "boolean",
      required: false,
      default: false,
      hidden: true,
      env: "SIGNAL_RESPOND_TO_ALL_MESSAGES",
      flag: "signal-respond-to-all-messages",
    },
    {
      key: "signal.maxMessageLength",
      label: "Max Message Length",
      description: "Maximum characters per Signal message",
      type: "number",
      required: false,
      default: 0,
      hidden: true,
      env: "SIGNAL_MAX_MESSAGE_LENGTH",
      flag: "signal-max-message-length",
    },
    {
      key: "signal.includeReplyContext",
      label: "Include Reply Context",
      description: "Include the quoted message when building the AI prompt",
      type: "boolean",
      required: false,
      default: true,
      hidden: true,
      env: "SIGNAL_INCLUDE_REPLY_CONTEXT",
      flag: "signal-include-reply-context",
    },
    {
      key: "signal.includeChannelContext",
      label: "Include Channel Context",
      description: "Include recent conversation when building the AI prompt",
      type: "boolean",
      required: false,
      default: true,
      hidden: true,
      env: "SIGNAL_INCLUDE_CHANNEL_CONTEXT",
      flag: "signal-include-channel-context",
    },
    {
      key: "signal.channelContextCount",
      label: "Channel Context Count",
      description: "Number of recent messages to include as conversation context",
      type: "number",
      required: false,
      default: 10,
      hidden: true,
      env: "SIGNAL_CHANNEL_CONTEXT_COUNT",
      flag: "signal-channel-context-count",
    },
    {
      key: "signal.multiMessageDelimiter",
      label: "Multi-Message Delimiter",
      description: "Delimiter used to split long responses into multiple messages",
      type: "string",
      required: false,
      default: "|||",
      hidden: true,
      env: "SIGNAL_MULTI_MESSAGE_DELIMITER",
      flag: "signal-multi-message-delimiter",
    },
    {
      key: "signal.multiMessageDelayMs",
      label: "Multi-Message Delay",
      description: "Delay in milliseconds between multi-message parts",
      type: "number",
      required: false,
      default: 1500,
      hidden: true,
      env: "SIGNAL_MULTI_MESSAGE_DELAY_MS",
      flag: "signal-multi-message-delay-ms",
    },
  ],
};

const bootstrap: PackageBootstrapModule = {
  metadata: {
    name: "signal",
    description: "Signal platform adapter backed by signal-cli JSON-RPC daemon.",
    version: "0.1.0",
  },
  kind: "platform",
  modulePath: "src/mod.ts",
  configSchema,
};

export default bootstrap;
