import type { ConfigSchema, PackageBootstrapModule } from "../../core/types.ts";

const configSchema: ConfigSchema = {
  module: "session",
  label: "Session Platform",
  fields: [
    {
      key: "session.mnemonic",
      label: "Session Mnemonic",
      description:
        "13-word mnemonic seed phrase for your Session bot account. If omitted, a new random identity is generated and persisted automatically.",
      type: "string",
      required: false,
      secret: true,
      env: "SESSION_MNEMONIC",
      flag: "session-mnemonic",
    },
    {
      key: "session.displayName",
      label: "Session Display Name",
      description: "Display name for the bot on the Session network",
      type: "string",
      required: false,
      default: "Missy",
      env: "SESSION_DISPLAY_NAME",
      flag: "session-display-name",
    },
    {
      key: "session.commandPrefix",
      label: "Command Prefix",
      description: "Prefix for text commands",
      type: "string",
      required: false,
      default: "!M!",
      env: "SESSION_COMMAND_PREFIX",
      flag: "session-command-prefix",
    },
    {
      key: "session.mentionOnly",
      label: "Mention Only",
      description: "Only respond in groups when mentioned",
      type: "boolean",
      required: false,
      default: true,
      hidden: true,
      env: "SESSION_MENTION_ONLY",
      flag: "session-mention-only",
    },
    {
      key: "session.respondToAllMessages",
      label: "Respond to All Messages",
      description: "Respond to every message in Session groups",
      type: "boolean",
      required: false,
      default: false,
      hidden: true,
      env: "SESSION_RESPOND_TO_ALL_MESSAGES",
      flag: "session-respond-to-all-messages",
    },
    {
      key: "session.maxMessageLength",
      label: "Max Message Length",
      description: "Maximum characters per Session message",
      type: "number",
      required: false,
      default: 0,
      hidden: true,
      env: "SESSION_MAX_MESSAGE_LENGTH",
      flag: "session-max-message-length",
    },
    {
      key: "session.includeReplyContext",
      label: "Include Reply Context",
      description: "Include the quoted message when building the AI prompt",
      type: "boolean",
      required: false,
      default: true,
      hidden: true,
      env: "SESSION_INCLUDE_REPLY_CONTEXT",
      flag: "session-include-reply-context",
    },
    {
      key: "session.includeChannelContext",
      label: "Include Channel Context",
      description: "Include recent conversation when building the AI prompt",
      type: "boolean",
      required: false,
      default: true,
      hidden: true,
      env: "SESSION_INCLUDE_CHANNEL_CONTEXT",
      flag: "session-include-channel-context",
    },
    {
      key: "session.channelContextCount",
      label: "Channel Context Count",
      description: "Number of recent messages to include as conversation context",
      type: "number",
      required: false,
      default: 10,
      hidden: true,
      env: "SESSION_CHANNEL_CONTEXT_COUNT",
      flag: "session-channel-context-count",
    },
    {
      key: "session.multiMessageDelimiter",
      label: "Multi-Message Delimiter",
      description: "Delimiter used to split long responses into multiple messages",
      type: "string",
      required: false,
      default: "|||",
      hidden: true,
      env: "SESSION_MULTI_MESSAGE_DELIMITER",
      flag: "session-multi-message-delimiter",
    },
    {
      key: "session.multiMessageDelayMs",
      label: "Multi-Message Delay",
      description: "Delay in milliseconds between multi-message parts",
      type: "number",
      required: false,
      default: 1500,
      hidden: true,
      env: "SESSION_MULTI_MESSAGE_DELAY_MS",
      flag: "session-multi-message-delay-ms",
    },
    {
      key: "session.autoAcceptRequests",
      label: "Auto-Accept Conversation Requests",
      description: "Automatically accept incoming Session conversation requests",
      type: "boolean",
      required: false,
      default: true,
      hidden: true,
      env: "SESSION_AUTO_ACCEPT_REQUESTS",
      flag: "session-auto-accept-requests",
    },
  ],
};

const bootstrap: PackageBootstrapModule = {
  metadata: {
    name: "session",
    description:
      "Session messenger platform adapter backed by @session.js/client.",
    version: "0.1.0",
  },
  kind: "platform",
  modulePath: "src/mod.ts",
  configSchema,
};

export default bootstrap;
